name: CD

on:
  push:
    tags:
      - '*'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: create file list
        id: files_list
        run: |
          mkdir output
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/build-your-ai-coding-assistant.docx ${{ steps.files_list.outputs.files }}

      - name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/build-your-ai-coding-assistant.docx
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
